### ISSUE TITLE
Failed to load a language-css package grammar

### ISSUE THREAD

**Issue by Pedro-Sanchez-Cardenas** [atom/language-css#164]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: [language-css](https://github.com/atom/language-css) package 0.44.0

### Stack Trace

Failed to load a language-css package grammar

```
At The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter-css/build/Release/tree_sitter_css_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/language-css/grammars/tree-sitter-css.json

Error: The module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/tree-sitter-css/build/Release/tree_sitter_css_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /app.asar/node_modules/tree-sitter-css/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-css/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3217918)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359778)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359619)
    at u (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:580347)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581600
    at ELECTRON_ASAR.js:555:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)
  at /app.asar/node_modules/language-css/grammars/tree-sitter-css.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.36 
highlight-selected 0.16.0 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
```

**Comment by rsese** [comment]
Can you quit and restart Atom and let us know if you still see the error?
