### ISSUE TITLE
Failed to load a language-css package grammar

### ISSUE THREAD

**Issue by jabedini** [atom/language-css#172]
[Enter steps to reproduce:]

1. as soon as i open atom
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-css](https://github.com/atom/language-css) package 0.44.4

### Stack Trace

Failed to load a language-css package grammar

```
At The specified module could not be found.
\\?\C:\Users\jabedini\AppData\Local\atom\app-1.54.0\resources\app.asar.unpacked\node_modules\tree-sitter-css\build\Release\tree_sitter_css_binding.node in C:\Users\jabedini\AppData\Local\atom\app-1.54.0\resources\app.asar\node_modules\language-css\grammars\tree-sitter-css.json

Error: The specified module could not be found.
\\?\C:\Users\jabedini\AppData\Local\atom\app-1.54.0\resources\app.asar.unpacked\node_modules\tree-sitter-css\build\Release\tree_sitter_css_binding.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /app.asar/node_modules/tree-sitter-css/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-css/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:3582512)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:361047)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:360888
    at u (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:581750)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:583003
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)
  at /app.asar/node_modules/language-css/grammars/tree-sitter-css.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
git-clone 0.2.0 
```

**Comment by darangi** [comment]
Does this happen when you open atom in safe mode? `atom --safe`

**Comment by jabedini** [comment]
No but it was multiple error that came and one was an existing issue -related to loading modules- . Once i used the resolve from that this issue also got fixes. So they may have been connected. I don't know where i can check for the history of the errors i received. but in short i went to atom program folder on C:\ and opened bin and then opened atom.cmd then closed and re-opened atom and all issues were resolved.
